### ISSUE TITLE
Help with MediaSourceFactory for java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/source/ads/AdsMediaSource$MediaSourceFactory;

### ISSUE THREAD

**Issue by cabhara** [google/ExoPlayer#9781]
I'm implementing the IMA AdLoader into an existing project. I'm using the sample code on https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side

Unfortunately I have to use version 2.15.1, as my project does not compile with exoPlayer 2.16.0+ (gradle version issues)
implementation 'com.google.android.exoplayer:exoplayer-core:2.15.1'
implementation 'com.google.android.exoplayer:exoplayer-ui:2.15.1'
implementation 'com.google.android.exoplayer:extension-ima:2.15.1'

When calling this line in initializePlayer():
```
MediaSourceFactory mediaSourceFactory =
                new DefaultMediaSourceFactory(dataSourceFactory)
                        .setAdsLoaderProvider(unusedAdTagUri -> adsLoader)
                        .setAdViewProvider(playerView);
```

my app crashes with the error below.

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/source/ads/AdsMediaSource$MediaSourceFactory;`

Question: Is there documentation on how to initialize the the media Source Factory so that it would work in a version smaller than 2.16.0? I tried reading through the changes and applying older code, but nothing has worked out so far.

**Comment by tonihei** [comment]
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/source/ads/AdsMediaSource$MediaSourceFactory;

This class was deleted in ExoPlayer 2.11.0. 

As already pointed out in [#9726](https://github.com/google/ExoPlayer/issues/9726#issuecomment-981755572), it looks as if your gradle setup includes multiple versions of the same file, and in particular it seems that there are multiple versions of ExoPlayer's IMA extension (yours in 2.15.1 and another one with a version < 2.11.0). These clash at build time as in #9726 or at runtime like in this issue. 

Please check you app dependencies (by running something like `./gradlew app:dependencies`) to see where this may be coming from.

**Comment by cabhara** [comment]
thanks for the tip!

**Comment by cabhara** [comment]
I removed expo-av from my react native project (now have to replace all video and audio playing by expo-av with exoplayer) as expo-av was using exoplayer 2.9.2 under the hood. project is compiling and working now.
