### ISSUE TITLE
Gradle task generateCombinedJavadoc fails

### ISSUE THREAD

**Issue by adesentenac** [google/ExoPlayer#9638]
Running `./gradlew generateCombinedJavadoc` fails with the following error:
```
ExoPlayer/extensions/mediasession/src/main/java/com/google/android/exoplayer2/ext/mediasession/MediaSessionConnector.java:123: error: cannot find symbol
        PlaybackStateCompat.ACTION_SET_PLAYBACK_SPEED
                           ^
  symbol:   variable ACTION_SET_PLAYBACK_SPEED
  location: class PlaybackStateCompat
1 error

> Task :generateCombinedJavadoc FAILED

```

This happens on ExoPlayer tags r2.15.1 and r2.15.0 (it was working in r2.14.2), it also fails in the dev-v2 branch.

**Comment by tonihei** [comment]
The issue is caused by a versioning conflict on `androix:media:` between `extension-cast` and `extension-mediasession`. 

If you want to build the Javadoc, you can add `api 'androidx.media:media:' + androidxMediaVersion` to the `build.gradle` file of `extension-cast`. This is only needed for the Javadoc generation, hence we don't want to submit this change.
