### ISSUE TITLE
Cannot find imports after upgrade

### ISSUE THREAD

**Issue by Okuro3499** [google/ExoPlayer#11284]
### Bug

I have integrated this library in a project (https://github.com/open-learning-exchange/myplanet.git) and it was working fine and building succesfully and after upgrading com.google.android.exoplayer:exoplayer from 2.7.2 to 2.19.1. I am not able to get some exoplayer imports specifically
```
import com.google.android.exoplayer2.ExoPlayerFactory;
import com.google.android.exoplayer2.source.ExtractorMediaSource;
import com.google.android.exoplayer2.ui.SimpleExoPlayerView;
import com.google.android.exoplayer2.upstream.DefaultHttpDataSourceFactory;
```
this is the implementation in my code https://github.com/open-learning-exchange/myplanet/blob/master/app/src/main/java/org/ole/planet/myplanet/ui/viewer/VideoPlayerActivity.java

this is the error I get when I build in android studio
```
/home/gideon/Desktop/planetCodes/myplanet/app/build/generated/data_binding_base_class_source_out/debug/out/org/ole/planet/myplanet/databinding/ActivityExoPlayerVideoBinding.java:12: error: cannot find symbol
import com.google.android.exoplayer2.ui.SimpleExoPlayerView;
                                       ^
  symbol:   class SimpleExoPlayerView
  location: package com.google.android.exoplayer2.ui
/home/gideon/Desktop/planetCodes/myplanet/app/build/generated/data_binding_base_class_source_out/debug/out/org/ole/planet/myplanet/databinding/ActivityExoPlayerVideoBinding.java:23: error: cannot find symbol
  public final SimpleExoPlayerView exoPlayerSimple;
               ^
  symbol:   class SimpleExoPlayerView
  location: class ActivityExoPlayerVideoBinding
/home/gideon/Desktop/planetCodes/myplanet/app/build/generated/data_binding_base_class_source_out/debug/out/org/ole/planet/myplanet/databinding/ActivityExoPlayerVideoBinding.java:26: error: cannot find symbol
      @NonNull SimpleExoPlayerView exoPlayerSimple) {
               ^
  symbol:   class SimpleExoPlayerView
  location: class ActivityExoPlayerVideoBinding
/home/gideon/Desktop/planetCodes/myplanet/app/build/generated/data_binding_base_class_source_out/debug/out/org/ole/planet/myplanet/databinding/ActivityExoPlayerVideoBinding.java:59: error: cannot find symbol
      SimpleExoPlayerView exoPlayerSimple = ViewBindings.findChildViewById(rootView, id);
      ^
  symbol:   class SimpleExoPlayerView
  location: class ActivityExoPlayerVideoBinding
```

**Comment by icbaker** [comment]
These symbols have been removed in various versions since 2.7.2. These removals are all documented in the release notes, including the recommended alternative in each case: https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md

The `com.google.android.exoplayer2` project is now deprecated. We are not accepting any new issues in this project. Please file new issues in the `androidx.media3` GitHub project instead: https://github.com/androidx/media/issues
