### ISSUE TITLE
Deprecated prepare(source, resetPosition, resetState) method not working as expected

### ISSUE THREAD

**Issue by master255** [google/ExoPlayer#9202]
@ojw28 After I upgraded from version 2.12 to 2.14, nothing works.
The video does not display:
The onVideoSizeChanged event doesn't happen.
Music does not play:
The onAudioSessionIdChanged event does not happen.

There is no way to change the track. Previously I set a new MediaItem and playback started. Now it doesn't work.

Has the module gone completely into commercial development? Should I stay on 2.12?

**Comment by master255** [comment]
If I just update the libraries, I get this error:
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/drm/DefaultDrmSessionManagerProvider;
        at com.google.android.exoplayer2.source.hls.HlsMediaSource$Factory.<init>(HlsMediaSource.java:132)
        at com.google.android.exoplayer2.source.hls.HlsMediaSource$Factory.<init>(HlsMediaSource.java:121)
        at com.media.library.customViews.ExoGPlayer.initPlayer(ExoGPlayer.java:232)

**Comment by master255** [comment]
@ojw28 Oliver, you can work without me?

**Comment by master255** [comment]
@ojw28 How to change a track without a release?

**Comment by marcbaechinger** [comment]
Thanks for your report.

Can you give me some more info about which `EventListener` you have registered with which API (`AnalyticsListener` vs. `VideoListener`)? Which of the two `onVideoSizeChanged `callback do you listen to? `onVideoSizeChanged(VideoSize videoSize) or onVideoSizeChanged( int width, int height, int unappliedRotationDegrees, float pixelWidthHeightRatio)`? Similar for the audioSessionId. In want event do you expect the call on which listener?

**Comment by master255** [comment]
@marcbaechinger **First question: How to change a track without a release?**

**Comment by marcbaechinger** [comment]
If you are using the `DefaultTrackSelector` provided by the library, setting new parameters does invalidate the track selection and makes the player ask for a new selection the next time a track selection is required (like before a next segment or chunk needs loading). 

If you implemented you own `TrackSelector` a `TrackSelector.InvalidationListener` is passed to the init method of your custom implementation. This can be called to tell the player to request a new selection.

This should work without calling release. Why are you thinking a release is required? Please let me know what you try to achieve if my above comment is not sufficient.

**Comment by master255** [comment]
@marcbaechinger I have one URL link and sometimes I need to change it.
Previously I did this:

```
mMediaPlayer.prepare(
   progressiveSource.createMediaSource(
       new MediaItem.Builder().setUri(Uri.parse(path)).build()), !haveStartPosition, false);
```

player started playing... (now it doesn't start playing)
now do i need to change the trackselector as well? Or what?

**Comment by marcbaechinger** [comment]
Ah, no sorry. :) That was a misunderstanding. We use the term 'track' for adaptive tracks internally. I've seen the stack trace above and thought it was about HLS.  Please disregard my comment above. 

The case you are describing with calling the deprecated prepare method works for me when I try this in the demo app.
In your case does `!haveStartPosition` evaluate to true or false when it is not working? It works for me with both, true or false actually. What do you see in the logs? Like any transitions of the state of the player that look suspicious?

**Comment by master255** [comment]
@marcbaechinger I do this:

```
mMediaPlayer.prepare(
   progressiveSource.createMediaSource(
       new MediaItem.Builder().setUri(Uri.parse(path)).build()), !haveStartPosition, false);
       
```
after that, I change the link and do it again. The player doesn't play. 
Version 2.12 plays.
Version 2.14.1 does not play

What to do?

**Comment by marcbaechinger** [comment]
I'd suggest to migrate to the new API:

```
MediaItem mediaItem = new MediaItem.Builder().setUri(Uri.parse(path)).build();
mMediaPlayer.setMediaItem(mediaItem, haveStartPosition ? startPosition : C.TIME_UNSET);
mMediaPlayer.prepare();
```

Can you try whether that works?

If you want me to look into the issue in more detail, please answer my question from above. I wasn't clear, sorry.

**Comment by master255** [comment]
@marcbaechinger I checked the migration. It doesn't work in the same way.

haveStartPosition = false

**Comment by master255** [comment]
@marcbaechinger What to do? Is this bug reproducing for you?

**Comment by master255** [comment]
@marcbaechinger @ojw28 Where is the answer? You need your player now. I have vlc. Although it has bugs, but it doesn't cut sound and video quality like your module.

**Comment by marcbaechinger** [comment]
We are a small group of engineers answering issues here on GitHub. We have to prioritize, because our time is scarce compared to the number of issues. So we have to kind of stack rank what to look into next. So, talking to you as a friend, if your aim is to speed up processing of your issue, then changing your language from unacceptable to decently cooperative would be a low hanging fruit for you to achieve this. I don't want to ask for 'friendliness', because lets do baby steps and then eventually, when the time is right for it we become a master.

I will see when I have time to look into your issue and will add a comment here when this is the case. Until then consider any further unfriendly or offensive comments from your side as an effective means to further delay processing of your issues.

**Comment by master255** [comment]
@marcbaechinger I'm asking a simple question - "do you understand everything and Is this bug reproducing for you?". 
I wait a week for an answer: yes or no.
Then you write that I am rude.
But maybe it's not about me? All of the players programmers I know don't respect your team because you only think about money and go your own way of development for big companies.
The list of pull requests has been full of requests for merge very useful features for several years now.
I get annoyed when I see bad programmers. This is your team right now.
You simply don't test what you write. If I were you, I would have made a masterpiece a long time ago, and you still have problems with time. It's annoying and laughable.

But of course I will try to respect the culture of communication, because otherwise you have a quick bot here, which will not allow me to write. In this you have succeeded.

**Comment by master255** [comment]
@marcbaechinger When other developers have made a business out of your faults and are making money out of it, it's worth thinking about.

**Comment by marcbaechinger** [comment]
When I try the case you describe I can not repro like mentioned in [my comment above](https://github.com/google/ExoPlayer/issues/9202#issuecomment-882554856).

To describe in detail what I did and what my expectation is:

I prepare the player with the deprecated method like you describe. I`m using an mp4 each time I prepare the player. There is an initale preparation:

```
DefaultMediaSourceFactory mediaSourceFactory =
    new DefaultMediaSourceFactory(/* context= */ this);
player.prepare(
    mediaSourceFactory.createMediaSource(mediaItems.get(0)),
    /* resetPosition= */ !haveStartPosition,
    /* resetState= */ false);
```
Then playback is expected to start and after ten seconds I hit a button in the app that triggers the code in the next snippet which I believe is what you reported is not working:

```
DefaultMediaSourceFactory mediaSourceFactory =
        new DefaultMediaSourceFactory(/* context= */ this);
MediaItem mediaItem =
    MediaItem.fromUri("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4");
Log.d("issue9202", "current position: " + player.getCurrentPosition());
player.prepare(
    mediaSourceFactory.createMediaSource(mediaItem),
    /* resetPosition= */ false,
    /* resetState= */ false);
Log.d("issue9202", "current position: " + player.getCurrentPosition());
```

My expectation is now that while playback is ongoing (state READY), the former playlist with a single source is replaced by another single source playlist. The player is then prepared and because we do not reset the position (`/* resetPosition= */ false`) playback starts at the position at which I hit the button which is about 10 seconds from the beginning.

The log produced by ExoPlayer is below.

```
D/EventLogger: timeline [eventTime=0.00, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
D/EventLogger:   period [?]
D/EventLogger:   window [?, seekable=false, dynamic=true]
D/EventLogger: ]
D/EventLogger: mediaItem [eventTime=0.00, mediaPos=0.00, window=0, reason=PLAYLIST_CHANGED]
D/EventLogger: state [eventTime=0.01, mediaPos=0.00, window=0, BUFFERING]

D/EventLogger: renderedFirstFrame [eventTime=1.00, mediaPos=0.00, window=0, period=0, Surface(name=null)/@0xa84b0b8]
D/EventLogger: isPlaying [eventTime=1.22, mediaPos=0.12, window=0, period=0, true]

D/issue9202: current position: 10614
D/EventLogger: timeline [eventTime=11.65, mediaPos=10.61, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
D/EventLogger:   period [?]
D/EventLogger:   window [?, seekable=false, dynamic=true]
D/EventLogger: ]
D/EventLogger: positionDiscontinuity [eventTime=11.65, mediaPos=10.61, window=0, reason=REMOVE, PositionInfo:old [window=0, period=0, pos=10614], PositionInfo:new [window=0, period=0, pos=10614]]
D/EventLogger: mediaItem [eventTime=11.66, mediaPos=10.61, window=0, reason=PLAYLIST_CHANGED]
D/EventLogger: state [eventTime=11.66, mediaPos=10.61, window=0, BUFFERING]
D/EventLogger: isPlaying [eventTime=11.66, mediaPos=10.61, window=0, false]
D/issue9202: current position: 10614
D/EventLogger: renderedFirstFrame [eventTime=12.70, mediaPos=10.61, window=0, period=0, Surface(name=null)/@0xa84b0b8]
D/EventLogger: state [eventTime=12.85, mediaPos=10.74, window=0, period=0, READY]
```

The interesting bits wrapped up below:

playlist changed twice as expected by setting the source twice (observe the mediaPos also):
```
D/EventLogger: timeline [eventTime=0.00, mediaPos=0.00, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
D/EventLogger:   period [?]
D/EventLogger:   window [?, seekable=false, dynamic=true]
D/EventLogger: ]
[...]
D/EventLogger: timeline [eventTime=11.65, mediaPos=10.61, window=0, periodCount=1, windowCount=1, reason=PLAYLIST_CHANGED
D/EventLogger:   period [?]
D/EventLogger:   window [?, seekable=false, dynamic=true]
D/EventLogger: ]
```

state looks good (note the mediaPos again):
```
D/EventLogger: state [eventTime=0.01, mediaPos=0.00, window=0, BUFFERING]
[...]
D/EventLogger: state [eventTime=11.66, mediaPos=10.61, window=0, BUFFERING]
[...]
D/EventLogger: state [eventTime=12.85, mediaPos=10.74, window=0, period=0, READY]
```

rendered first frame twice:
```
D/EventLogger: renderedFirstFrame [eventTime=1.00, mediaPos=0.00, window=0, period=0, Surface(name=null)/@0xa84b0b8]
D/EventLogger: renderedFirstFrame [eventTime=12.70, mediaPos=10.61, window=0, period=0, Surface(name=null)/@0xa84b0b8]
```

Can you confirm that I have tried to repro what you are describing is not working? If not, can you please give me some more details on what you are doing and what the expectation is? 

If my test fixture  is indeed what you do but does not work for you, can you please use the [EventLogger](https://exoplayer.dev/listening-to-player-events.html#using-eventlogger) in the same way that I did above and send the logs over to me? It gets easier for me to see what-s going on in your app.

**Comment by master255** [comment]
@marcbaechinger onAudioSessionIdChanged does not work. I checked in your demo.

```
  private class PlayerEventListener implements Player.Listener {

    @Override
    public void onAudioSessionIdChanged(int audioSessionId) {
      Log.d("TEST123", "TEST1234");
    }

    @Override
    public void onVideoSizeChanged(VideoSize videoSize) {
      Log.d("TEST123", "TEST123");
    }
```

**Comment by marcbaechinger** [comment]
`onAudioSessionIdChanged` is only called if the audio ID actually is changed by the app by calling `SimpleExoPlayer.setAudioSessionId`. Please see also #8712.

If you want to know the audio session ID that is internally created you can do so just after building `SimpleExoPlayer`:

```
player =
    new SimpleExoPlayer.Builder(/* context= */ this, renderersFactory)
        .setMediaSourceFactory(mediaSourceFactory)
        .setTrackSelector(trackSelector)
         .build();
Log.d("9202", "getAudioSessionId:  " + player.getAudioSessionId());
```

Does your app call `SimpleExoPlayer.setAudioSessionId` and you don't see the callback being called?
