### ISSUE TITLE
Cast demo app play dash video error

### ISSUE THREAD

**Issue by volkansahin45** [google/ExoPlayer#4994]
### Issue description
When try to play dash video on cast it gives an error

### Reproduction steps
Connect cast device.
Click add button.
Add the dash video
Click Ok and close dialog.
Click Dash in the playlist.

### Version of ExoPlayer being used
2.9.0

### Device(s) and version(s) of Android being used
Samsung Galaxy S8 Plus Android 8.0.0

### A full bug report captured from the device
Sent via email

**Comment by jaisonfdo** [comment]
Do we have any updates on this issue? The app is crashing with the following exception

`2019-04-08 15:48:20.098 20770-20770/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.exoplayer2.castdemo, PID: 20770
    java.lang.IllegalArgumentException: Invalid mime type: mp4a.40.2
        at com.google.android.exoplayer2.util.MimeTypes.getTopLevelType(MimeTypes.java:390)
        at com.google.android.exoplayer2.util.MimeTypes.isAudio(MimeTypes.java:127)
        at com.google.android.exoplayer2.util.MimeTypes.getTrackType(MimeTypes.java:320)
        at com.google.android.exoplayer2.ext.cast.CastPlayer.updateTracksAndSelections(CastPlayer.java:628)
        at com.google.android.exoplayer2.ext.cast.CastPlayer.updateInternalState(CastPlayer.java:568)
        at com.google.android.exoplayer2.ext.cast.CastPlayer$StatusListener.onStatusUpdated(CastPlayer.java:773)
        at com.google.android.gms.cast.framework.media.zzs.onStatusUpdated(Unknown Source:5)
        at com.google.android.gms.internal.cast.zzdx.onStatusUpdated(Unknown Source:604)
        at com.google.android.gms.internal.cast.zzdx.zzo(Unknown Source:506)
        at com.google.android.gms.cast.framework.media.RemoteMediaClient.onMessageReceived(Unknown Source:367)
        at com.google.android.gms.internal.cast.zzdj.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.google.android.gms.internal.cast.zzez.dispatchMessage(Unknown Source:6)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`

Can you suggest any work around for this specific issue?

**Comment by AquilesCanta** [comment]
Hi @jaisonfdo, sorry for not updating this issue before. This should be [fixed](https://github.com/google/ExoPlayer/commit/774c01d02046993e824aa31e2cb49bfc1283bc78#diff-28aa8fcdfda6da09b45c0ca527ecf206) in the dev-v2 branch. Please give it a try and let me know if you can still reproduce.

**Comment by jaisonfdo** [comment]
Hey @AquilesCanta thanks for the immediate response, yup it's working as intended.

**Comment by volkansahin45** [comment]
@AquilesCanta thanks for fix

**Comment by huynhtanloc2612** [comment]
> Hi @jaisonfdo, sorry for not updating this issue before. This should be [fixed](https://github.com/google/ExoPlayer/commit/774c01d02046993e824aa31e2cb49bfc1283bc78#diff-28aa8fcdfda6da09b45c0ca527ecf206) in the dev-v2 branch. Please give it a try and let me know if you can still reproduce.

Hi @AquilesCanta, I had the same error when using cast extension of version 2.9.0
"java.lang.IllegalArgumentException: Invalid mime type: mp4a.40.2"

And I also applied your suggestion with the version 2.10.1 of cast extension.
implementation 'com.google.android.exoplayer:exoplayer:2.10.1'
compile 'com.google.android.exoplayer:extension-cast:2.10.1'

 but I got errors in Java compiler
"error: cannot find symbol class SessionAvailabilityListener"

It shows that SessionAvailabilityListener cannot be found in version 2.10.1 of cast extension but it can be found in version 2.9.x and earlier.

Could you give me some advice?

Thanks,
Loc Huynh

**Comment by AquilesCanta** [comment]
It's possible that it [got moved](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/ext/cast/SessionAvailabilityListener.html).

**Comment by huynhtanloc2612** [comment]
Thanks @AquilesCanta 
I removed "CastPlayer" class from below sentence and it worked in the version of 2.10.1
Before: CastPlayer.SessionAvailabilityListener()
After: SessionAvailabilityListener()
Thanks a lot!
